[tool.isort]
profile = "black"

[tool.black]
line-length=90
target-version=["py38", "py39", "py310", "py311"]
include='\.pyi?$'
exclude='''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
'''
